# Usar una imagen base de Java
FROM openjdk:17-jdk-slim

# Crear directorio de trabajo
WORKDIR /app

# Copiar el JAR generado
COPY target/bakend-0.0.1-SNAPSHOT.jar backend.jar

# Exponer el puerto del backend
EXPOSE 8080

# Comando para ejecutar la aplicación
CMD ["java","-Xms512m", "-Xmx2g", "-jar", "backend.jar"]
